name: daily-update          # 워크플로 이름

on:
  schedule:                 # 매일 03:30 UTC (12:30 KST) 실행
    - cron: '30 3 * * *'
  workflow_dispatch:        # 수동 실행 버튼

permissions:                # ⬅️  github-actions[bot] 에 push 권한 부여
  contents: write

concurrency:                # 동시에 2개 이상 실행되지 않도록
  group: data-update
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃 (전체 히스토리)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Python 설치
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 의존 패키지
      - run: pip install -r requirements.txt

      # 4. 데이터 수집 · 커밋 · push
      - name: run fetch_data & commit
        env:
          FRED_KEY: ${{ secrets.FRED_KEY }}
          ECOS_KEY: ${{ secrets.ECOS_KEY }}
          MOLIT_KEY: ${{ secrets.MOLIT_KEY }}
          RTMS_AREA: ${{ secrets.RTMS_AREA }}
        run: |
          set -e

          # 새 CSV 생성
          rm -f data/all_data.csv
          python fetch_data.py

          # Git 설정
          git config user.name  "data-bot"
          git config user.email "bot@users.noreply.github.com"

          git add data/all_data.csv
          git commit -m "auto: data $(date -u +'%F %T')" || exit 0

          # 원격 변경이 있으면 rebase 후 push
          git pull --rebase --autostash origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}
