name: daily-update
on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

permissions:
  contents: write                # ← NEW

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}

      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - run: pip install -r requirements.txt

      - name: run fetch & commit
        env:
          FRED_KEY:  ${{ secrets.FRED_KEY }}
          ECOS_KEY:  ${{ secrets.ECOS_KEY }}
        run: |
          rm -f data/all_data.csv
          python fetch_data.py
          git config user.name  "bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/all_data.csv
          git commit -m "auto: data $(date -u +'%F %T')" || echo "no change"
          git push
