name: daily-update
on:
  schedule:
    - cron: "30 3 * * *"   # 매일 12:30 KST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: pip install -r requirements.txt

    - name: Run fetch_data & commit
      run: |
        python fetch_data.py
        git config user.name "auto-bot"
        git config user.email "bot@users.noreply.github.com"
        git add data/all_data.csv
        git commit -m "auto: update data $(date -u +'%Y-%m-%d %H:%M')" || echo "no changes"
        git push
      env:
        ECOS_KEY: ${{ secrets.ECOS_KEY }}
